First version of msocket C++ wrapper
cogu/msocket pull request #1
Opened 2017-03-05 16:39 UTC by svrd

including echo server/client example

2017-03-05 17:05 UTC, cogu requested changes
lite småsaker behöver fixas samt förslag på namnändringar

2017-03-05 17:05 UTC, cogu commented on examples/echo_cpp/echo_client.cpp
> +* Copyright (c) 2014-2017 Pierre Svärd
2017 istället för 2014-2017?

2017-03-05 17:05 UTC, cogu commented on examples/echo_cpp/echo_server.cpp
> +* Copyright (c) 2014-2017 Pierre Svärd
2017

2017-03-05 17:05 UTC, cogu commented on inc/MsocketCpp.h
> +* Copyright (c) 2014-2017 Pierre Svärd
2017

2017-03-05 17:05 UTC, cogu commented on inc/MsocketServerCpp.h
> +* Copyright (c) 2014-2017 Pierre Svärd
2017

2017-03-05 17:05 UTC, cogu commented on src/MsocketCpp.cpp
> +* Copyright (c) 2014-2017 Pierre Svärd
2017

2017-03-05 17:05 UTC, cogu commented on inc/MsocketCpp.h
> +class Msocket {
Är det inte snyggare med MSocket istället för Msocket? Samma gälller alla andra klasser som MSocketServer osv.

2017-03-05 17:05 UTC, cogu commented on inc/MsocketCpp.h
> +   struct HandlerD {
Vad står D:et för?

2017-03-05 17:05 UTC, cogu commented on inc/MsocketCpp.h
> +* \file      MsocketCpp.cpp
Vad sägs om att använda MSocket.hpp istället för MsocketCpp.h?
Kommentaren här skulle då behöva ändras från .cpp -> .hpp

2017-03-05 17:05 UTC, cogu commented on src/MsocketCpp.cpp
> +#include <MsocketCpp.h>
Använd "" istället för <> när du gör user include. <> skall användas för system-includes
-->#include "MSocket.hpp"

2017-03-05 17:05 UTC, cogu commented on src/MsocketServerCpp.cpp
> +* \file      MsocketServerCpp.cpp
Cpp.cpp känns lite reduntant ;-)

2017-03-07 18:32 UTC, svrd commented on inc/MsocketCpp.h
> +* \file      MsocketCpp.cpp
Ja det blir bättre...

2017-03-07 18:32 UTC, svrd commented on inc/MsocketCpp.h
> +class Msocket {
Jo :+1:

2017-03-07 18:34 UTC, svrd commented on inc/MsocketCpp.h
> +   struct HandlerD {
D som i Data för structar. Men då ska man nog egentligen ha E för Enum, C för Class, I för Interface, etc. Kan använda T för alla typer så är det samma suffix som i din c-kod.

2017-03-07 18:35 UTC, svrd commented on src/MsocketCpp.cpp
> +#include <MsocketCpp.h>
Ja, det var nog någon eclipse-automatik inblandad här

2017-03-07 19:14 UTC, cogu approved these changes
Kanon!

2017-03-07 19:14 UTC, merged